Chatter/StudyBuddy.Web.RazorPages/Models/Subject.cs
using System;
using System.Collections.Generic;

namespace StudyBuddy.Web.RazorPages.Models
{
    public partial class Subject
    {
        public int Subjectid { get; set; }
        public string Title { get; set; }

        public ICollection<Teaching> Teachings { get; set; }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Admin;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.AdminPage
{
    public class AddModel : PageModel
    {
        private IAdminActivity _adminActivity;

        [BindProperty]
        public string Title { get; set; }

        public string ErrorAdd { get; set; }

        public AddModel(IAdminActivity adminActivity)
        {
            _adminActivity = adminActivity;
        }

        public IActionResult OnPost()
        {
            try
            {
                _adminActivity.AddSubject(Title);
                return RedirectToPage("/AdminPage/Requests");
            }
            catch(ArgumentException exc)
            {
                ModelState.AddModelError("ErrorAdd", exc.Message);
                return Page();
            }
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Teacher;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class AddModel : PageModel
    {
        private ITeacherActivity _teacherActivity;

        [BindProperty]
        public int SubjectID { get; set; }

        //property for adding custom subject
        [BindProperty, Required(ErrorMessage = "Subject title is required")]
        public string SubjectTitle { get; set; }
        public List<SelectListItem> Options { get; set; }

        public AddModel(ITeacherActivity teacherActivity)
        {
            _teacherActivity = teacherActivity;
        }

        public async Task<IActionResult> OnGetAsync(int teacherID)
        {
            IList<Subject> availableSubjects = await _teacherActivity.GetAvailableSubjects(teacherID);
            Options = availableSubjects.Select(s =>
                                                    new SelectListItem
                                                    {
                                                        Value = s.Subjectid.ToString(),
                                                        Text = s.Title
                                                    }).ToList();
            return Page();
        }

        public IActionResult OnPost(int teacherID)
        {
            _teacherActivity.AddSubject(teacherID, SubjectID);

            return RedirectToPage("./Subjects");
        }

        //request new custom subject
        public IActionResult OnPostRequest(int teacherID)
        {
            _teacherActivity.AddSubject(teacherID, SubjectTitle);
            return RedirectToPage("./Subjects");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class IndexModel : PageModel
    {
        private readonly IUserInfoLoader _userInfoLoader;
        private IHttpContextAccessor _httpContextAccessor;

        public IndexModel(IUserInfoLoader userInfoLoader, IHttpContextAccessor httpContextAccessor)
        {
            _userInfoLoader = userInfoLoader;
            _httpContextAccessor = httpContextAccessor;
        }

        public string TeacherName { get; private set; }

        public async Task OnGetAsync()
        {
            TeacherName = await _userInfoLoader.GetUserNameById(int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value));
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class ProfileModel : PageModel
    {
        private readonly StudyBuddy.Web.RazorPages.Data.StudiBudiContext _context;

        public ProfileModel(StudyBuddy.Web.RazorPages.Data.StudiBudiContext context)
        {
            _context = context;
        }

        //todo: teacher id is hardcoded but it should be received after user logs in
        private int teacherID = 3;
        public List<string> MySubjects;

        public async Task OnGetAsync()
        {
            IList<Teaching> teachings = await _context.Teaching.ToListAsync();
            IList<Subject> subjects = await _context.Subject.ToListAsync();

            MySubjects = (from t in teachings
                         join s in subjects on t.Subjectid equals s.Subjectid
                         where t.Userid == teacherID
                         select s.Title).ToList();
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Share.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Teacher;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class ShareModel : PageModel
    {
        private ITeacherActivity _teacherActivity;
        public SelectList SubjectsTitles { get; set; }
        public int TeacherID { get; set; }

        [BindProperty]
        public string SubjectTitle { get; set; }

        [BindProperty, Required]
        public string Question { get; set; }

        [BindProperty, Required]
        public string Answer { get; set; }

        public ShareModel(ITeacherActivity teacherActivity)
        {
            _teacherActivity = teacherActivity;
        }

        public async Task OnGet(int teacherID)
        {
            SubjectsTitles = new SelectList(await _teacherActivity.GetMySubjects(teacherID));
        }

        public async Task<IActionResult> OnPostAsync(int teacherID)
        {
            await _teacherActivity.Share(teacherID, SubjectTitle, Question, Answer);
            return RedirectToPage("./TeacherChat");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Subjects.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Teacher;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class SubjectsModel : PageModel
    {
        private ITeacherActivity _teacherActivity;
        private IHttpContextAccessor _httpContextAccessor;

        public SubjectsModel(ITeacherActivity teacherActivity, IHttpContextAccessor httpContextAccessor)
        {
            _teacherActivity = teacherActivity;
            _httpContextAccessor = httpContextAccessor;
            TeacherID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
        }
        public int TeacherID { get; set; }
        public List<string> MySubjects = new List<string>();

        public async Task OnGetAsync()
        {
            MySubjects = await _teacherActivity.GetMySubjects(TeacherID);
        }

        public async Task<IActionResult> OnPostDeleteAsync(string subjectTitle)
        {
            await _teacherActivity.DeleteSubject(TeacherID, subjectTitle);
            return Redirect("/TeacherPage/Subjects");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/TeacherChat.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Entities;
using StudyBuddy.Web.RazorPages.Logic.Teacher;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class TeacherChatModel : PageModel
    {
        private readonly IQuestionLoader _questionLoader;
        private readonly IUserInfoLoader _userInfoLoader;
        private readonly IQuestionAnswerRegister _answerRegister;
        private readonly ITeacherActivity _teacherActivity;
        private IHttpContextAccessor _httpContextAccessor;

        public int TeacherID;

        [BindProperty]
        public string Answer { get; set; }


        //properties for reporting student
        [BindProperty, Required]
        public string ReportMessage { get; set; }
        [BindProperty]
        public string StudentName { get; set; }
        public string ReportError { get; set; }

        public TeacherChatModel(IQuestionLoader questionLoader, IUserInfoLoader userInfoLoader, IQuestionAnswerRegister answerRegister,
            IHttpContextAccessor httpContextAccessor, ITeacherActivity teacherActivity)
        {
            _questionLoader = questionLoader;
            _userInfoLoader = userInfoLoader;
            _answerRegister = answerRegister;
            _teacherActivity = teacherActivity;
            _httpContextAccessor = httpContextAccessor;
        }

        public List<QuestionGroup> Questions { get; set; }

        public async Task<IActionResult> OnGetAsync(string message = null)
        {
            TeacherID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Questions = await _questionLoader.GetGroupedQuestionsForTeacher(await _userInfoLoader.GetEncryptedUserNameById(TeacherID));

            if(message != null)
            {
                ModelState.AddModelError("ReportError", message);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int questionID)
        {
            try
            {
                await _answerRegister.RegisterAnswer(questionID, Answer);
            }
            catch(ArgumentException exc)
            {
                return RedirectToAction("OnGetAsync", new { message = exc.Message});
            }

            return RedirectToPage();
        }

        public IActionResult OnPostReport()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("OnGetAsync", new { message = "Report message cannot be empty!" });
            }

            _teacherActivity.ReportStudent(StudentName, ReportMessage);

            return RedirectToPage();
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/TeacherPoints.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Ratings;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class TeacherPointsModel : PageModel
    {
        private ITeacherPoints _teacherPoints;
        private IHttpContextAccessor _httpContextAccessor;
        private IPoints _points;
        private int teacherID;
        public int TotalPoints { get; set; }
        public TeacherPointsModel(ITeacherPoints teacherPoints, IPoints points, IHttpContextAccessor httpContextAccessor)
        {
            _teacherPoints = teacherPoints;
            _httpContextAccessor = httpContextAccessor;
            _points = points;
        }

        public IList<Question> Question { get;set; }

        public async Task OnGetAsync()
        {
            teacherID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Question = await _teacherPoints.GetHistoryByTeacherID(teacherID);
            TotalPoints = await _points.GetTotalPoints(teacherID);
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/TeacherProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Models;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Profile;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class TeacherProfileModel : PageModel
    {

        [BindProperty]
        public string NewPasswords { get; set; }

        [BindProperty]
        public string NewPasswords2 { get; set; }


        [BindProperty]
        public string OldPasswords { get; set; }

        [BindProperty]
        public string Name { get; set; }


        [TempData]
        public string Msgs { get; set; }

        private IHttpContextAccessor _httpContextAccessor;
        private readonly IUserInfoLoader _userInfoLoader;
        private ILoginChecker _loginchekers;
        private IProfile _getPasswords;
        private readonly ILoginChecker _logincheker;


        private int TeacherID { get; set; }

        public string TeacherName { get; set; }






        public TeacherProfileModel(IUserInfoLoader userInfoLoader, IProfile getPassword, ILoginChecker logincheker, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _getPasswords = getPassword;
            _logincheker = logincheker;
            _userInfoLoader = userInfoLoader;
            TeacherID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
        }


        public async Task OnGetAsync()
        {
            TeacherName = await _userInfoLoader.GetUserNameById(TeacherID);
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if(!_getPasswords.IsStringsMaches(NewPasswords,NewPasswords2) && !_getPasswords.IsStringsMaches(NewPasswords, OldPasswords))
            {
                Msgs = "bad data, try again";
                return RedirectToPage();
            }else if(!_getPasswords.IsPasswordMaches(OldPasswords,TeacherID))
            {
                Msgs = "bad data, try again";
                return RedirectToPage();
            }
            await _getPasswords.PasswordChange(NewPasswords, TeacherID);
            Msgs = "Password changed";
            return RedirectToPage();

        }

        public async Task<ActionResult> OnPostKazkasAsync()
        {

              if (_getPasswords.IsStringGood(OldPasswords) && _getPasswords.IsStringGood(Name) && _getPasswords.IsPasswordMaches(OldPasswords, TeacherID) )
              {//tikrina ar vardas tinkamas ir ar slaptazodis tinkamas

                  if (_logincheker.GetProfessionByUserName(Name) != null)
                  {
                      Msgs = "Bad Name";
                      return RedirectToPage();
                  }
                  else
                  {

                      await _getPasswords.NameChange(Name, TeacherID);
                        Msgs = "Name changed";
                        return RedirectToPage("/TeacherPage/TeacherProfile");
                  }
              }
              else
              {
                  Msgs = "Try again";
                  return RedirectToPage();
              }

        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Add.cshtml
@page "{teacherID:int}"
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.AddModel

@{
    ViewData["Title"] = "Add";
    Layout = "_LayoutWithoutNavigation";
}
        <hr />
        <fieldset>
            <legend>Choose subject to add</legend>

            <div class="row">
                <div class="col-md-4">
                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <select class="form-control" asp-for="SubjectID" asp-items="Model.Options"></select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-success">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </fieldset>
        <hr />
        <fieldset>
            <legend>If you miss something, request new subject!</legend>

            <div class="row">
                <div class="col-md-4">
                    <form method="post">
                        <input type="text" class="form-control-plaintext" asp-for="SubjectTitle" />
                        <input type="submit" class="btn btn-outline-success" asp-page-handler="Request" value="Request" />
                        <span style="color:red" asp-validation-for="@Model.SubjectTitle"></span>
                    </form>
                </div>
            </div>
        </fieldset>
        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Index.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.IndexModel

@{
    ViewData["Title"] = "IndexTeacherPage";
}

        <h1 style="text-align:center">Hello @Html.DisplayFor(model => model.TeacherName)!</h1>

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Profile.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.ProfileModel

@{
    ViewData["Title"] = "My subjects";
}
<h1> Teacher Subjects </h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Subject
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.MySubjects) { 
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item)
                </td>
            </tr>
        }

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
    </tbody>
</table>

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Share.cshtml
@page

@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.ShareModel
@{
    ViewData["Title"] = "Share";
    Layout = "~/Pages/Shared/_LayoutWithoutNavigation.cshtml";
}
        <form method="post">
            <hr />
            <br />
            <a asp-page="./TeacherChat">Go back</a>
            <br />
            <hr />

            <div class="form-group">
                <h3> Choose subject </h3>
                <select class="form-control" selected asp-for="SubjectTitle" asp-items="Model.SubjectsTitles">
                </select>
            </div>
            <div class="form-group">
                <br />
                <h3>Enter the question</h3>
                <textarea maxlength="500" rows="3" class="form-control" asp-for="Question" style="border:dashed 6px #FF7851"></textarea>
                <span style="color:red" asp-validation-for="@Model.Question"></span>
            </div>
            <div class="form-group">
                <br />
                <h3>Enter the answer</h3>
                <textarea maxlength="500" rows="3" class="form-control" asp-for="Answer" style="border:dashed 6px #78C2AD;"> </textarea>
                <span style="color:red" asp-validation-for="@Model.Answer"></span>
            </div>
            <div class="form-group" asp-route-teacherID="@Model.TeacherID">
                <input type="submit" value="Share" class="btn btn-success" />
            </div>
        </form>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Subjects.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.SubjectsModel

@{
    ViewData["Title"] = "My subjects";
}
        <fieldset>
            <legend>Teacher Subjects</legend>
            <form action="/TeacherPage/Add">
                <input type="submit" class="btn btn-outline-success" asp-page="/TeacherPage/Add" value="Add new subject" asp-route-teacherID="@Model.TeacherID" />
            </form>
        </fieldset>


        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="table-primary">
                        Subject
                    </th>
                    <th class="table-primary">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.MySubjects)
                {
                    <tr class="table-dark">
                        <td>
                            @Html.DisplayFor(modelItem => item)
                        </td>

                        <td>
                            <form method="post">
                                <button type="submit" class="btn btn-danger" asp-page-handler="Delete" asp-route-subjectTitle=@item.ToString()>Delete</button>
                            </form>
                        </td>
                    </tr>
                }
                @section Scripts {
                    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                }
            </tbody>
        </table>

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/TeacherChat.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.TeacherChatModel

@{
    ViewData["Title"] = "TeacherChat";
}

<style>
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 400px; /* Could be more or less, depending on screen size */
        height: 350px;
    }


    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
</style>
    <fieldset>
        <legend>Inbox</legend>
    </fieldset>

    <div style="background-color:bisque">
        <p>Students keep asking same question? </p>
        <a class="nav-link" asp-page="/TeacherPage/Share" asp-route-teacherID="@Model.TeacherID">
            Click here to share the question and your answer with everyone else!
        </a>
    </div>



    <span style="color:red"> @Html.ValidationMessageFor(model => model.ReportError) </span>
    <table class="table table-hover">

        <tbody>
            @foreach (var group in Model.Questions)
            {
                <tr>
                    <td class="table-primary">
                        <strong> @Html.DisplayFor(modelItem => group.Key.Name)</strong>, @Html.DisplayFor(modelItem => group.Key.SubjectTitle)
                    </td>
                    <td class="table-primary">
                        <button id="report" onclick="reportStudent('@group.Key.Name')" class="btn btn-danger">Report Student</button>
                    </td>
                </tr>

                @foreach (var item in group.Questions)
                {
                    <tr>
                        <td class="table-dark">
                            <textarea maxlength="500" readonly rows="3" class="form-control" style="border:dashed 6px #FF7851"> @Html.DisplayFor(modelItem => item.Message)</textarea>
                        </td>

                        @if (item.Status == 0)
                        {
                            <td class="table-dark">
                                <form metohd="post" asp-route-questionID="@item.QuestionID">
                                    <textarea asp-for="Answer" rows="3" class="form-control" style="border:dashed 6px #FF7851;"></textarea>
                                    <br />
                                    <input type="submit" value="send" class="btn btn-outline-success" />
                                </form>
                            </td>
                        }
                        else
                        {
                            <td class="table-dark">
                                <textarea maxlength="500" class="form-control" style="color:#56CC9D;border:dashed 6px #78C2AD" readonly > @Html.DisplayFor(modelItem => item.Answer)</textarea>
                            </td>
                        }

                    </tr>
                }
            }
        </tbody>
    </table>

    <div id="reportModal" class="modal">

        <div class="modal-content">
            <span id="closeButton" class="close">&times;</span>
            <form metohd="post" asp-page-handler="Report">
                <input asp-for="StudentName" id="student-to-report" type="text" hidden />
                <br />
                Why you want to report this student? <br />
                <textarea maxlength="500" class="form-control" style="color:#56CC9D" asp-for="ReportMessage"></textarea>
                <br />
                <input id="submitButton" type="submit" value="Report" class="btn btn-outline-success" />
            </form>
        </div>
    </div>
    <script>
        var reportModal = document.getElementById("reportModal");
        var reportButton = document.getElementById("report");
        var studentToReport = document.getElementById("student-to-report");
        var submitButton = document.getElementById("submitButton");
        var closeButton = document.getElementById("closeButton");


        function reportStudent(studentName) {
            reportModal.style.display = "block";
            studentToReport.value = studentName;
        }

        submitButton.onclick = function () {
            reportModal.style.display = "none";
        }

        closeButton.onclick = function () {
            reportModal.style.display = "none";
        }
    </script>

    @section scripts{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <partial name="_ValidationScriptsPartial" />
        <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    }

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/TeacherPoints.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.TeacherPage.TeacherPointsModel

@{
    ViewData["Title"] = "TeacherPoints";
}
        <fieldset>
            <Legend>Look what others thinks about your answers</Legend>

            <Legend> You have  <span class="badge badge-primary badge-pill" style="background-color: #6CC3D5">@Model.TotalPoints</span> points</Legend>
        </fieldset>
        <table class="table table-hover">
            <thead>
                <tr class="table-dark">
                    <th>
                        Student
                    </th>
                    <th>
                        Subject
                    </th>
                    <th>
                        Question
                    </th>
                    <th>
                        Your answer
                    </th>
                    <th>
                        Points received
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Question)
                {
                    <tr>
                        <td class="table-dark">
                            <span class="badge badge-primary badge-pill">@Html.DisplayFor(modelItem => item.StudentName)</span>
                        </td>
                        <td class="table-dark">
                            @Html.DisplayFor(modelItem => item.SubjectTitle)
                        </td>
                        <td class="table-dark">
                            @Html.DisplayFor(modelItem => item.Message)
                        </td>
                        <td class="table-dark">
                            <span class="badge badge-primary badge-pill">  @Html.DisplayFor(modelItem => item.Answer)</span>
                        </td>
                        <td class="table-dark" style="text-align:center">
                            <span class="badge badge-primary badge-pill" style="background-color: #6CC3D5"> @Html.DisplayFor(modelItem => item.Points)</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>