Chatter/StudyBuddy.Web.RazorPages/Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StudyBuddy.Web.RazorPages.Models
{
    public class Report
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Message { get; set; }

        [ForeignKey("UserID")]
        public User User { get; set; }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Admin;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.AdminPage
{
    public class AddModel : PageModel
    {
        private IAdminActivity _adminActivity;

        [BindProperty]
        public string Title { get; set; }

        public string ErrorAdd { get; set; }

        public AddModel(IAdminActivity adminActivity)
        {
            _adminActivity = adminActivity;
        }

        public IActionResult OnPost()
        {
            try
            {
                _adminActivity.AddSubject(Title);
                return RedirectToPage("/AdminPage/Requests");
            }
            catch(ArgumentException exc)
            {
                ModelState.AddModelError("ErrorAdd", exc.Message);
                return Page();
            }
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.AdminPage
{
    public class IndexModel : PageModel
    {
        private IUserInfoLoader _userInfoLoader;
        private IHttpContextAccessor _httpContextAccessor;
        public IndexModel(IUserInfoLoader userInfoLoader, IHttpContextAccessor httpContextAccessor)
        {
            _userInfoLoader = userInfoLoader;
            _httpContextAccessor = httpContextAccessor;
        }

        public string AdminName { get; set; }

        public async Task OnGetAsync()
        {
            AdminName = await _userInfoLoader.GetUserNameById(int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value));
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Reports.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Admin;
using StudyBuddy.Web.RazorPages.Logic.Entities;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.AdminPage
{
    public class ReportsModel : PageModel
    {
        //services
        private IReportsLoader _reportsLoader;
        private IAdminActivity _adminActivity;

        //properties
        public IList<Report> Reports { get; set; }
        public IList<ReportedUser> ReportedUsers { get; set; }

        //properties for user banning
        [BindProperty]
        public int UserID { get; set; }

        public ReportsModel(IReportsLoader reportsLoader, IAdminActivity adminActivity)
        {
            _reportsLoader = reportsLoader;
            _adminActivity = adminActivity;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Reports = await _reportsLoader.GetReports();
            ReportedUsers = await _adminActivity.GetReportedUsers();

            return Page();
        }

        public IActionResult OnPost(int userID)
        {
            _adminActivity.SuspendUser(userID, DateTime.Now);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostCancelAsync(int userID)
        {
            await _adminActivity.CancelBan(userID);
            return RedirectToPage("/AdminPage/Reports");
        }

        public async Task<IActionResult> OnPostDeleteAsync(int reportID)
        {
            await _adminActivity.DeleteReport(reportID);
            return RedirectToPage("/AdminPage/Reports");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Requests.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Admin;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.AdminPage
{
    public class RequestsModel : PageModel
    {
        private IAdminActivity _adminActivity;
        private IRequestLoader _requestLoader;

        public IList<SubjectRequest> Requests { get; set; }
        public IList<Subject> Subjects { get; set; }

        public string ErorrApprove { get; set; }

        public RequestsModel(IAdminActivity adminActivity, IRequestLoader requestLoader)
        {
            _adminActivity = adminActivity;
            _requestLoader = requestLoader;
        }

        public async Task<IActionResult> OnGetAsync(string message = "")
        {
            Subjects = await _requestLoader.GetSubjects();
            Requests = await _requestLoader.GetRequests();

            if(message != "")
            {
                ModelState.AddModelError("ErorrApprove", message);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostApproveAsync(int requestID)
        {
            try
            {
                await _adminActivity.ApproveNewSubjectRequest(requestID);
            }
            catch(ArgumentException exc)
            {
                ModelState.AddModelError("ErorrApprove", exc.Message);
                return RedirectToAction("OnGetAsync", new { message = exc.Message });
            }
            
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDenyAsync(int requestID)
        {
            await _adminActivity.DenyNewSubjectRequest(requestID);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int subjectID)
        {
            await _adminActivity.DeleteSubject(subjectID);
            return RedirectToPage();
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/TeacherPage/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic.Teacher;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.TeacherPage
{
    public class AddModel : PageModel
    {
        private ITeacherActivity _teacherActivity;

        [BindProperty]
        public int SubjectID { get; set; }

        //property for adding custom subject
        [BindProperty, Required(ErrorMessage = "Subject title is required")]
        public string SubjectTitle { get; set; }
        public List<SelectListItem> Options { get; set; }

        public AddModel(ITeacherActivity teacherActivity)
        {
            _teacherActivity = teacherActivity;
        }

        public async Task<IActionResult> OnGetAsync(int teacherID)
        {
            IList<Subject> availableSubjects = await _teacherActivity.GetAvailableSubjects(teacherID);
            Options = availableSubjects.Select(s =>
                                                    new SelectListItem
                                                    {
                                                        Value = s.Subjectid.ToString(),
                                                        Text = s.Title
                                                    }).ToList();
            return Page();
        }

        public IActionResult OnPost(int teacherID)
        {
            _teacherActivity.AddSubject(teacherID, SubjectID);

            return RedirectToPage("./Subjects");
        }

        //request new custom subject
        public IActionResult OnPostRequest(int teacherID)
        {
            _teacherActivity.AddSubject(teacherID, SubjectTitle);
            return RedirectToPage("./Subjects");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Add.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.AdminPage.AddModel

@{
    ViewData["Title"] = "Add";
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}
    <body style="background-color:#343a40;">

        <h1>Enter new subject title</h1>

        <form method="post">
            <input type="text" asp-for="Title" />
            <input type="submit" value="Add" />
            <span style="color:red"> @Html.ValidationMessageFor(model => model.ErrorAdd) </span>
        </form>
        </body>
        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Index.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.AdminPage.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}
<body style="background-color:#343a40;">

    <h1 style="text-align:center">Hello @Html.DisplayFor(model => model.AdminName)!</h1>
    </body>

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Reports.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.AdminPage.ReportsModel

@{
    ViewData["Title"] = "Reports";
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Create two unequal columns that floats next to each other */
    .column {
        float: left;
        padding: 10px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>
<body style="background-color:#343a40;">

    <div class="row">
        <div class="column" style="padding-right:50px">
            <h1>Reports</h1>
            <table class="table" border="1">
                <thead>
                    <tr>
                        <th>
                            UserID
                        </th>
                        <th>
                            Message
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Reports)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserID)
                            </td>
                            <td>
                                <textarea maxlength="500" readonly> @Html.DisplayFor(modelItem => item.Message)</textarea>
                            </td>
                            <td>
                                <form method="post">
                                    <input type="submit" value="Delete" asp-page-handler="Delete" asp-route-reportID="@item.ID" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>


        <div class="column">
            <h1> Reported users </h1>
            <table class="table" border="1">
                <thead>
                    <tr>
                        <th>
                            UserID
                        </th>
                        <th>
                            Ban this user
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.ReportedUsers)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserID)
                            </td>

                            @if (item.Banned)
                            {
                                <td>
                                    Banned since:  @Html.DisplayFor(modelItem => item.Since)
                                    <form method="post">
                                        <input type="submit" value="Cancel" asp-page-handler="Cancel" asp-route-userID="@item.UserID" />
                                    </form>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <form method="post" asp-route-userID="@item.UserID">
                                        <input type="submit" value="Ban" />
                                    </form>
                                </td>
                            }

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    </body>

Chatter/StudyBuddy.Web.RazorPages/Pages/AdminPage/Requests.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.AdminPage.RequestsModel

@{
    ViewData["Title"] = "Requests";
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Create two unequal columns that floats next to each other */
    .column {
        float: left;
        padding: 10px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>
<body style="background-color:#343a40;">

    <div class="row">
        <div class="column" style="padding-right:50px">
            <h1>Requests</h1>
            @if (Model.Requests.Count == 0)
            {
                <h3> There are no requests! </h3>
            }
            else
            {
                <span style="color:red"> @Html.ValidationMessageFor(model => model.ErorrApprove) </span>
                <table class="table" border="1">
                    <thead>
                        <tr>
                            <th>
                                UserID
                            </th>
                            <th>
                                Message
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Requests)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserID)
                                </td>
                                <td>
                                    <textarea maxlength="500" readonly> @Html.DisplayFor(modelItem => item.Title)</textarea>
                                </td>
                                <td>
                                    <form method="post">
                                        <input type="submit" value="Approve" asp-page-handler="Approve" asp-route-requestID="@item.ID" />
                                    </form>
                                    <form method="post">
                                        <input type="submit" value="Deny" asp-page-handler="Deny" asp-route-requestID="@item.ID" />
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }

        </div>


        <div class="column">
            <h1> Existing subjects </h1>
            <table class="table" border="1">
                <thead>
                    <tr>
                        <th>
                            Subject title
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Subjects)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>

                            <td>
                                <form method="post">
                                    <input type="submit" value="Delete" asp-page-handler="Delete" asp-route-subjectID="@item.Subjectid" />
                                </form>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    </body>
    @section scripts{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <partial name="_ValidationScriptsPartial" />
        <script src="~/lib/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.min.js"></script>
    }