Chatter/StudyBuddy.Web.RazorPages/Models/FAQ.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StudyBuddy.Web.RazorPages.Models
{
    public class FAQ
    {
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public int SubjectID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }

        //current count of answered questions
        public int Answered { get; set; }

        //current points
        public int Points { get; set; }

        [ForeignKey("TeacherID")]
        public User User { get; set; }

        [ForeignKey("SubjectID")]
        public Subject Subject { get; set; }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Ask.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StudyBuddy.Web.RazorPages.Logic;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class AskModel : PageModel
    {
        private IQuestionRegister _questionRegister;

        [BindProperty]
        public string Message { get; set; }

        public string MessageError { get; set; }

        public AskModel(IQuestionRegister questionRegister)
        {
            _questionRegister = questionRegister;
        }

        public IActionResult OnPost(string teacherName, int studentID, string subjectTitle)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                _questionRegister.Ask(studentID, teacherName, Message, subjectTitle);
            }
            catch(ArgumentException exc)
            {
                ModelState.AddModelError("MessageError", exc.Message);
                return Page();
            }
            

            return RedirectToPage("/StudentPage/StudentChat");
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/FAQ.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Entities;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class FAQModel : PageModel
    {
        private IStudentActivity _studentActivity;
        public bool All { get; set; }

        public List<StudentFAQ> StudentFAQs { get; set; }
        public FAQModel(IStudentActivity studentActivity)
        {
            _studentActivity = studentActivity;
        }
        public async Task OnGet(bool all = false)
        {
            StudentFAQs = await _studentActivity.GetFAQs(all);
            All = all;
        }

        public IActionResult OnPostViewMoreAsync()
        {
            return RedirectToAction("OnGet()", new { all = true });
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Inbox.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Entities;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class InboxModel : PageModel
    {
        private IQuestionLoader _questionLoader;
        private IUserInfoLoader _userInfoLoader;
       
        public List<QuestionGroup> Questions { get; set; }

        public InboxModel(IQuestionLoader questionLoader, IUserInfoLoader userInfoLoader)
        {
            _questionLoader = questionLoader;
            _userInfoLoader = userInfoLoader;
        }


        public async Task OnGetAsync(int studentID)
        {
            Questions = await _questionLoader.GetGroupedQuestionsForStudent(await _userInfoLoader.GetEncryptedUserNameById(studentID));
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class IndexModel : PageModel
    {
        private readonly IUserInfoLoader _userInfoLoader;
        private IHttpContextAccessor _httpContextAccessor;

        public IndexModel(IUserInfoLoader userInfoLoader, IHttpContextAccessor httpContextAccessor)
        {
            _userInfoLoader = userInfoLoader;
            _httpContextAccessor = httpContextAccessor;
        }

        public string StudentName { get; private set; }

        public async Task OnGetAsync()
        {
            StudentName = await _userInfoLoader.GetUserNameById(int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value));
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentChat.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Entities;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class StudentChatModel : PageModel
    {
        private IStudentActivity _studentActivity;
        private IHttpContextAccessor _httpContextAccessor;

        public IList<TeacherAndSubject> TeachersAndSubjects { get; set; }

        public SelectList SubjectsTitles { get; set; }

        public int StudentID { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SubjectTitleFilter { get; set; } //table filter

        public StudentChatModel(IStudentActivity studentActivity, IHttpContextAccessor httpContextAccessor)
        {
            _studentActivity = studentActivity;
            _httpContextAccessor = httpContextAccessor;
             StudentID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
        }
        public async Task OnGetAsync()
        {
            List<TeacherAndSubject> teachersAndSubjects = await _studentActivity.GetTeachersAndSubjects();
            teachersAndSubjects =_studentActivity.FilterTeachersAndSubjects(SubjectTitleFilter, teachersAndSubjects);
            SubjectsTitles = new SelectList(await _studentActivity.GetSubjectsTitles());
            TeachersAndSubjects = teachersAndSubjects;
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Logic.Profile;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class StudentProfileModel : PageModel
    {


        [BindProperty]
        public string NewPasswords { get; set; }

        [BindProperty]
        public string NewPasswords2 { get; set; }


        [BindProperty]
        public string OldPasswords { get; set; }

        [BindProperty]
        public string Name { get; set; }


        [TempData]
        public string Msgs { get; set; }

        private IHttpContextAccessor _httpContextAccessor;
        private readonly IUserInfoLoader _userInfoLoader;
        private ILoginChecker _loginchekers;
        private IProfile _getPasswords;
        private readonly ILoginChecker _logincheker;


        private int StudentID { get; set; }

        public string StudentName { get; set; }
        public string Profesion;





        public StudentProfileModel(IUserInfoLoader userInfoLoader, IProfile getPassword, ILoginChecker logincheker, IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
            _getPasswords = getPassword;
            _logincheker = logincheker;
            _userInfoLoader = userInfoLoader;
            
            
            StudentID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Profesion = _getPasswords.GetProfesionByID(StudentID);
        }


        public async Task OnGetAsync()
        {
            StudentName = await _userInfoLoader.GetUserNameById(StudentID);
            
        }

        public async Task<IActionResult> OnPostAsync()
        {

            if (!_getPasswords.IsStringsMaches(NewPasswords, NewPasswords2) && !_getPasswords.IsStringsMaches(NewPasswords, OldPasswords))
            {
                Msgs = "bad data, try again";
                return RedirectToPage();
            }
            else if (!_getPasswords.IsPasswordMaches(OldPasswords, StudentID))
            {
                Msgs = "bad data, try again";
                return RedirectToPage();
            }
            await _getPasswords.PasswordChange(NewPasswords, StudentID);
            Msgs = "Password changed";
            return RedirectToPage();

        }

        public async Task<ActionResult> OnPostNameAsync()
        {

            if (_getPasswords.IsStringGood(OldPasswords) && _getPasswords.IsStringGood(Name) && _getPasswords.IsPasswordMaches(OldPasswords, StudentID))
            {//tikrina ar vardas tinkamas ir ar slaptazodis tinkamas

                if (_logincheker.GetProfessionByUserName(Name) != null)
                {
                    Msgs = "Bad Name";
                    return RedirectToPage();
                }
                else
                {

                    await _getPasswords.NameChange(Name, StudentID);
                    Msgs = "Name changed";
                    return RedirectToPage("");
                }
            }
            else
            {
                Msgs = "Try again";
                return RedirectToPage();
            }

        }
    }

    
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentRate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudyBuddy.Web.RazorPages.Data;
using StudyBuddy.Web.RazorPages.Logic;
using StudyBuddy.Web.RazorPages.Models;

namespace StudyBuddy.Web.RazorPages.Pages.StudentPage
{
    public class StudentRateModel : PageModel
    {
        private IStudentPoints _studentPoints;
        private IHttpContextAccessor _httpContextAccessor;
        [BindProperty]
        public int Value { get; set; }

        public SelectList Options { get; set; }

        public StudentRateModel(IStudentPoints studentsPoints, IHttpContextAccessor httpContextAccessor)
        {
            _studentPoints = studentsPoints;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult OnGet()
        {
            Options = new SelectList(_studentPoints.GetValues());
            return Page();
        }

        public IActionResult OnPost(int questionID)
        {
            _studentPoints.RegisterPoints(questionID, Value);
            return RedirectToPage("/StudentPage/Inbox", new { studentID = int.Parse(_httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value) });
        }
    }
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Ask.cshtml
@page "{teacherName}/{subjectTitle}/{studentID:int}"
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.AskModel
@{
    ViewData["Title"] = "Ask";
    Layout = "_LayoutWithoutNavigation";
}


<form method="post">
    <fieldset>
        <legend>Ask a question!</legend>
        <div class="form-group">
    <label for="exampleTextarea">Your question...</label>
    <textarea class="form-control" id="exampleTextarea" rows="3" asp-for="Message" maxlength="500" style="border:dashed 6px #FF7851"></textarea>
        </div>
        <input type="submit" value="Send" class="btn btn-success" />
        <span style="color:red "badge badge-primary badge-pill""> @Html.ValidationMessageFor(model => model.MessageError) </span>
    </fieldset>
</form>

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/FAQ.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.FAQModel
@{
    ViewData["Title"] = "FAQ";
    Layout = "~/Pages/Shared/_LayoutStudent.cshtml";
}

<legend style="text-align:center">Frequently asked questions</legend>

<table class="table table-hover" border="1">
    <thead>
        <tr>
            <th scope="col" class="table-success">
                Teacher's information
            </th>
            <th scope="col" class="table-success">
                Subject
            </th>

            <th scope="col" class="table-success">
                Question
            </th>

            <th scope="col" class="table-success">
                Answer
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.StudentFAQs)
        {
            <tr>
                <td class="table-dark">
                    Name:  <span style="font-weight:bold;background-color: #FF7851" class="badge badge-primary badge-pill">@Html.DisplayFor(modelItem => item.Name)</span> <br />
                    <span style="font-style:italic">At the moment, when this question was posted teacher had:</span> <br />
                    Points: <span style="font-weight:bold;background-color: #6CC3D5" class="badge badge-primary badge-pill"> @Html.DisplayFor(modelItem => item.Points)</span> <br />
                    Answered questions: <span style="font-weight:bold" class="badge badge-primary badge-pill"> @Html.DisplayFor(modelItem => item.Answered)</span>
                </td>

                <td style="text-align:center" class="table-dark">
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>

                <td style="text-align:center" class="table-dark">
                    @Html.DisplayFor(modelItem => item.Question)
                </td>

                <td style="text-align:center" class="table-dark">
                    <span class="badge badge-primary badge-pill"> @Html.DisplayFor(modelItem => item.Answer)</span>
                </td>

            </tr>
        }
    </tbody>
</table>

@if (!Model.All)
{
    <div class="text-center">
        <form method="post">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="View more" asp-page-handler="ViewMore" />
        </form>
    </div>
}

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Inbox.cshtml
@page "{studentID:int}"
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.InboxModel

@{
    ViewData["Title"] = "Inbox";
    Layout = "_LayoutWithoutNavigation";
}
    <fieldset>
        <Legend>Inbox</Legend>
        <form action="./StudentChat">
            <input type="submit" class="btn btn-outline-success" asp-page="./StudentChat" style="text-align:center" align="middle" value="Go back" />
        </form>
    </fieldset>
    <table class="table table-hover">

        <tbody>
            @foreach (var group in Model.Questions)
            {
                <tr>
                    <td colspan="3" class="table-primary">
                        @Html.DisplayFor(modelItem => group.Key.Name),  @Html.DisplayFor(modelItem => group.Key.SubjectTitle)
                    </td>
                </tr>
                @foreach (var item in group.Questions)
                {
                    <tr>
                        <td class="table-dark">
                            <div class="form-group">
                                <textarea maxlength="500" rows="3" class="form-control" readonly style="border:dashed 6px #FF7851"> @Html.DisplayFor(modelItem => item.Message)</textarea>
                            </div>

                        </td>

                        @if (item.Status == 0)
                        {
                            <td class="table-dark">
                                <p style="color:#FF7851"> Not answered yet</p>
                            </td>
                        }
                        else
                        {
                            <td class="table-dark">
                                <div class="form-group">
                                    <textarea maxlength="500" style="color:#56CC9D;border:dashed 6px #78C2AD;" rows="3" class="form-control" readonly> @Html.DisplayFor(modelItem => item.Answer)</textarea>
                                </div>
                            </td>
                        }

                        @if (item.Points != 0)
                        {
                            <td class="table-dark">
                                Rated: @Html.DisplayFor(modelItem => item.Points)
                            </td>
                        }
                        else if (item.Status == 1)
                        {
                            <td class="table-dark">
                                <a asp-page="/StudentPage/StudentRate" asp-route-questionID="@item.QuestionID"> Rate the answer! </a>
                            </td>
                        }
                        else
                        {
                            <td class="table-dark">
                                Get answer and then rate it!
                            </td>
                        }

                    </tr>
                }
            }
        </tbody>
    </table>

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/Index.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.IndexModel

@{
    ViewData["Title"] = "IndexStudentPage";
}
    <h1 style="text-align:center">Hello @Html.DisplayFor(model => model.StudentName)!</h1>

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentChat.cshtml
@page

@model StudyBuddy.Web.RazorPages.Pages.StudentPage.StudentChatModel

@{
    ViewData["Title"] = "StudentChat";
}
        <form>
            <fieldset>
                <legend style="text-align:center">Questions</legend>
                <br />
                <form action="/StudentPage/Inbox">
                    <input type="submit" class="btn btn-outline-success" asp-page="/StudentPage/Inbox" asp-route-studentID="@Model.StudentID" style="text-align:center" align="middle" value="View my questions" />
                </form>
                <br />
                <div class="form-group">
                    <select class="form-control" asp-for="SubjectTitleFilter" asp-items="Model.SubjectsTitles">
                        <option value=""> All </option>
                    </select>
                </div>
                <input type="submit" value="Filter" class="btn btn-outline-success" />
            </fieldset>
        </form>
        <br />
        <table class="table table-hover" border="1">
            <thead>
                <tr>
                    <th scope="col" class="table-success">
                        Teacher Name
                    </th>

                    <th scope="col" class="table-success">
                        Unanswered questions
                    </th>

                    <th scope="col" class="table-success">
                        Subject
                    </th>

                    <th scope="col" class="table-success">
                        Points
                    </th>

                    <th scope="col" class="table-success">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TeachersAndSubjects)
                {
                    <tr>
                        <td class="table-dark" style="text-align:center">
                            @Html.DisplayFor(modelItem => item.TeacherName)
                        </td>

                        <td class="table-dark" style="text-align:center">
                            <span class="badge badge-primary badge-pill" style="background-color: #FF7851">@Html.DisplayFor(modelItem => item.UnansweredCount)</span>
                        </td>

                        <td class="table-dark" style="text-align:center">
                            @Html.DisplayFor(modelItem => item.SubjectTitle)
                        </td>

                        <td class="table-dark" style="text-align:center">
                            <span class="badge badge-primary badge-pill">@Html.DisplayFor(modelItem => item.Points)</span>
                        </td>

                        <td class="table-dark" style="text-align:center">
                            <a asp-page="/StudentPage/Ask"
                               asp-route-teacherName="@item.TeacherName" asp-route-subjectTitle="@item.SubjectTitle"
                               asp-route-studentID="@Model.StudentID" class="nav-link"> Ask question! </a>
                        </td>
                    </tr>
                }
                @section Scripts {
                    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                }
            </tbody>
        </table>

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentProfile.cshtml
@page
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.StudentProfileModel

@{
    ViewData["Title"] = "StudentProfile";
}
<fieldset>
    <Legend style="text-align:center">Profile</Legend>
</fieldset>
<!--
<style>
    .Vardas {
        background-color: blanchedalmond;
        color: black;
        margin: 20px;
        padding: 20px;
        border-radius: 8px;
    }

    .btn {
        border: none;
        background-color: inherit;
        padding: 14px 28px;
        font-size: 16px;
        cursor: pointer;
        display: inline-block;
        color: green;
    }

        .btn:hover {
            background: #eee;
        }

    .tables {
        border: none;
    }



    .Bak-Laikinas {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        display: flex;
        justify-content: center;
        align-content: center;
    }

    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 400px; /* Could be more or less, depending on screen size */
        height: 350px;
    }

    /* The Close Button */
    .closes {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .closes:hover,
        .closes:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
</style>

    -->


<body style="background-color: blanchedalmond">
    <div class="Vardas">
        <h2 style="text-align:center">HELLO, @Html.DisplayFor(model => Model.StudentName) </h2>
        <p align="center"><span class="badge badge-light"> TYPE: @Html.DisplayFor(model => Model.Profesion)</span></p>


    </div>

    <h3 style="text-align:center">ACOUNT DATA</h3>


    <div class="table">
        <table class="table-hover" align="center">
            <tr>
                <th >Name</th>
                <td >@Html.DisplayFor(model => Model.StudentName)</td>
                <td >
                    <button id="Name" class="btn btn-success">Change Name</button><!-- <a class="btn success" asp-page="/TeacherPage/TeacherProfileChangeName">Change Name</a> -->
                </td>
            </tr>

            <tr>
                <th >Password</th>

                <td >
                    ******
                </td>

                <td ><button id="Password" class="btn btn-success">Change Password</button><!-- <a class="btn success" asp-page="/TeacherPage/TeacherProfileChangePassword">Change Password</a> --></td>
            </tr>


        </table>


    </div>

    <h1>
        @TempData["Msgs"]
    </h1>

    <br />

    <!--popup for password-->
    <div id="myModal" class="modal">


        <div class="modal-content">
            <span class="closes">&times;</span>

            <form method="post">

                <label for="token">Old Password </label>
                <input type="password" asp-for="@Model.OldPasswords" class="form-control-plaintext" /><br />

                <label for="newPassword">New Password:</label>
                <input type="password" asp-for="@Model.NewPasswords" class="form-control-plaintext" /><br />

                <label for="RepeatPassword">Repeat Password:</label>
                <input type="password" asp-for="@Model.NewPasswords2" class="form-control-plaintext" /><br />

                <input type="submit" value="Change" class="btn btn-outline-success" /><br />
            </form>
        </div>

    </div>

    <!--popup for name-->
    <div id="myOtherModal" class="modal">


        <div class="modal-content">
            <span class="close">&times;</span>

            <form asp-page-handler="Name" method="post">

                <label for="newName">New Name</label>
                <input type="text" asp-for="@Model.Name" class="form-control-plaintext" /><br />


                <label for="token">Password </label>
                <input type="password" asp-for="@Model.OldPasswords" class="form-control-plaintext" /><br />


                <input type="submit" value="Change" class="btn btn-outline-success" /><br />

            </form>
        </div>
    </div>
</body>
    <!--makes pop up window to show-->
    <script>
        // Get the modal
        var modal = document.getElementById("myModal");
        var modalN = document.getElementById("myOtherModal");
        // Get the button that opens the modal
        var btn = document.getElementById("Password");
        var btnN = document.getElementById("Name");
        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("closes")[0];
        var spanN = document.getElementsByClassName("close")[0];
        // When the user clicks the button, open the modal
        btn.onclick = function () {
            modal.style.display = "block";
        }
        btnN.onclick = function () {
            modalN.style.display = "block";
        }
        // When the user clicks on <span> (x), close the modal
        span.onclick = function () {
            modal.style.display = "none";
        }
        spanN.onclick = function () {
            modalN.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
        window.onclick = function (event) {
            if (event.target == modalN) {
                modalN.style.display = "none";
            }
        }

    </script>

Chatter/StudyBuddy.Web.RazorPages/Pages/StudentPage/StudentRate.cshtml
@page "{questionID:int}"
@model StudyBuddy.Web.RazorPages.Pages.StudentPage.StudentRateModel

@{
    ViewData["Title"] = "StudentRate";
    Layout = "_LayoutWithoutNavigation";
}

        <h1>Thank you for choosing to leave a feedback!</h1>

        <form method="post">
            <select  class="form-control" asp-for="Value" asp-items="Model.Options"></select>
            <input type="submit" class="btn btn-success" value="Submit!" />
        </form>